/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "imu_sample.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(goldenform_ImuSample, goldenform_ImuSample, AUTO)


PB_BIND(goldenform_ImuSampleBatch, goldenform_ImuSampleBatch, 4)



