/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "imu_sample.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(formsync_ImuSample, formsync_ImuSample, AUTO)


PB_BIND(formsync_ImuSampleBatch, formsync_ImuSampleBatch, 4)



