M48
; DRILL file {KiCad 9.0.6} date 2026-02-28T15:56:16-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-28T15:56:16-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.660
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X72.661Y-68.86
X72.661Y-74.64
T2
X72.28Y-91.93
X72.36Y-54.182
X123.75Y-92.75
X123.8Y-53.9
M30
